version: '3.9'
services:
  dlc-link-attestor:
    image: public.ecr.aws/dlc-link/dlc-attestor:dev
    ports:
      - ${ATTESTOR_PORT:-8801}:8801
    volumes:
      - ./config.yaml:/app/attestor/config.yaml
    environment:
      'PORT': '8801'
      # Optional ATTESTOR_XPRIV: the extended private key to use for signing attestations
      # If none is provided, a random key will be generated
      'ATTESTOR_XPRIV': ${ATTESTOR_XPRIV}
      # Optional INFURA_API_KEY: the Infura API key to use for Ethereum transactions
      'INFURA_API_KEY': ${INFURA_API_KEY}
