# This is the compose file running as part of the automated GH workflow
version: '3.9'
services:
  postgresdlc:
    container_name: postgresdlc
    image: postgres:12
    hostname: postgresdlc
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: theraininspainstaysmainlyintheplain
      PGDATA: /data/postgres
    ports:
      - "5433:5433"
    command: -p 5433
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      static-network:
        ipv4_address: 172.20.128.8

  storageapi:
    container_name: storageapi
    hostname: storageapi
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/storage-api:${IMAGE_TAG}
    environment:
      RUST_LOG: 'debug'
      DATABASE_URL: 'postgresql://postgres:theraininspainstaysmainlyintheplain@postgresdlc:5433/postgres'
      MIGRATE: 'true'
    ports:
      - '8100:8100'
    entrypoint: '/app/storage-api'
    depends_on:
      postgresdlc:
        condition: service_healthy
    networks:
      static-network:
        ipv4_address: 172.20.128.1

  dlc-link-attestor-1:
    container_name: attestor-1
    hostname: attestor-1
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/dlc-attestor:${IMAGE_TAG}
    ports:
      - 8801:8801
    environment:
      'BRANCH': 'attestor-manager'
      'PORT': '8801'
      'DEV_ENDPOINTS_ENABLED': 'true'
      'PRIVATE_KEY': '575bdf41f62ba26af51bc1a3a8672e3b4e6d0401bbe8649936ef41a5257f2544'
      'STORAGE_API_ENABLED': 'true'
      'STORAGE_API_ENDPOINT': 'http://storageapi:8100'
      'CHAIN_1': '${CHAIN_1:-STACKS_MOCKNET}'
      'VERSION_1': '${VERSION_1:-1}'
      'API_KEY_1': '${API_KEY_1:-abcdef1234567890}'
    restart: on-failure
    depends_on:
      - storageapi
    networks:
      static-network:
        ipv4_address: 172.20.128.5

  dlc-link-attestor-2:
    container_name: attestor-2
    hostname: attestor-2
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/dlc-attestor:${IMAGE_TAG}
    ports:
      - 8802:8802
    environment:
      'BRANCH': 'attestor-manager'
      'PORT': '8802'
      'DEV_ENDPOINTS_ENABLED': 'true'
      'PRIVATE_KEY': '12cc65bd6db57f1a53ed501d146ac0c74bef695286371979a80280a20d25cf4f'
      'STORAGE_API_ENABLED': 'true'
      'STORAGE_API_ENDPOINT': 'http://storageapi:8100'
      'CHAIN_1': '${CHAIN_1:-STACKS_MOCKNET}'
      'VERSION_1': '${VERSION_1:-1}'
      'API_KEY_1': '${API_KEY_1:-abcdef1234567890}'
    restart: on-failure
    depends_on:
      - storageapi
    networks:
      static-network:
        ipv4_address: 172.20.128.6

  dlc-link-attestor-3:
    container_name: attestor-3
    hostname: attestor-3
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/dlc-attestor:${IMAGE_TAG}
    ports:
      - 8803:8803
    environment:
      'BRANCH': 'attestor-manager'
      'PORT': '8803'
      'DEV_ENDPOINTS_ENABLED': 'true'
      'PRIVATE_KEY': '4cbf3a503ccabe3de3e8dbaa449fcf84b1f6f42c085d86030510ae00281000d4'
      'STORAGE_API_ENABLED': 'true'
      'STORAGE_API_ENDPOINT': 'http://storageapi:8100'
      'CHAIN_1': '${CHAIN_1:-STACKS_MOCKNET}'
      'VERSION_1': '${VERSION_1:-1}'
      'API_KEY_1': '${API_KEY_1:-abcdef1234567890}'
    restart: on-failure
    depends_on:
      - storageapi
    networks:
      static-network:
        ipv4_address: 172.20.128.7

  blockchain-interface:
    container_name: blockchain-interface
    hostname: blockchain-interface
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/dlc-blockchain-interface:${IMAGE_TAG}
    ports:
      - 3000:3000
      - 3003:3003
    environment:
      - 'PORT=3000'
      - 'TEST_MODE_ENABLED=true'
      - 'ROUTER_WALLET_ADDRESS=http://router-wallet:8085'
      - 'CHAIN=STACKS_MOCKNET'
      - 'VERSION=1'
      - 'API_KEY=abcdef1234567890'
      - 'PRIVATE_KEY=6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01'
      - 'MOCKNET_ADDRESS=96.126.107.204:3999'
    depends_on:
      - dlc-link-attestor-1
      - dlc-link-attestor-2
      - dlc-link-attestor-3
    restart: on-failure
    networks:
      static-network:
        ipv4_address: 172.20.128.3

  router-wallet:
    container_name: router-wallet
    hostname: router-wallet
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/dlc-protocol-wallet:${IMAGE_TAG}
    ports:
      - 8085:8085
    environment:
      # For Internal DLC.Link Bitcoin Mocknet
      - 'ELECTRUM_API_URL=http://96.126.107.204:3002'
      # For Bitcoin Testnet
      # - "ELECTRUM_API_URL=https://blockstream.info/testnet/api"
      # For Bitcoin Mainnet
      # ELECTRUM_API_URL="https://blockstream.info/api"
      - 'BITCOIN_CHECK_INTERVAL_SECONDS=15'
      - 'BITCOIN_NETWORK=regtest'
      - 'RUST_LOG=warn,dlc_protocol_wallet=debug'
      - 'RUST_BACKTRACE=full'
      - 'STORAGE_API_ENABLED=true'
      - 'STORAGE_API_ENDPOINT=http://storageapi:8100'
      - 'CONTRACT_CLEANUP_ENABLED=false'
      - 'BLOCKCHAIN_INTERFACE_URL=http://blockchain-interface:3000'
      - 'XPRIV=${XPRIV}'
      - 'FINGERPRINT=${FINGERPRINT}'
      - 'WALLET_IP=172.20.128.2'
    depends_on:
      - postgresdlc
      - storageapi
      - blockchain-interface
    restart: on-failure
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    healthcheck:
      test: curl --fail http://router-wallet:8085/info || exit 1
      interval: 3s
      timeout: 10s
      retries: 10
      start_period: 5s

  integration-test:
    profiles:
      - it
    container_name: integration-test
    hostname: integration-test
    image: 903295530547.dkr.ecr.us-east-1.amazonaws.com/dlc-integration-test:${IMAGE_TAG}
    environment:
      - ENV=docker
      - HANDLE_ATTESTORS=true
      - SUCCESSFUL_ATTESTING=true
      - ELECTRUM_API_URL=http://96.126.107.204:3002
    depends_on:
      router-wallet:
        condition: service_healthy
    networks:
      static-network:
        ipv4_address: 172.20.128.9
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
