FROM rust:1.70 AS build

COPY . /app/dlc-stack/
WORKDIR /app/dlc-stack/

RUN rustup override set nightly
RUN cargo build --release --bin storage-api

FROM debian:bullseye-slim AS dlc-link-storage-api
RUN apt-get update && apt-get install -y openssl libpq-dev ca-certificates && apt-get clean
COPY --from=build /app/dlc-stack/target/release/storage-api /app/storage-api

WORKDIR /app
ENTRYPOINT ["/app/storage-api"]
